### ISSUE TITLE
404 links in various docs pages

### ISSUE THREAD

**Issue by julieg18** [iterative/mlem.ai#109]
Some of our doc pages have failing links
* https://mlem.ai/doc/api-reference/mlem-object ("Edit on Github" button)
* https://mlem.ai/doc/contributing/core (["Contributing to the Documentation"](https://mlem.ai/doc/user-guide/contributing/docs))
* https://mlem.ai/doc/user-guide/configuration ([`mlem config`](https://mlem.ai/doc/command-reference/config))
* https://mlem.ai/doc/user-guide/remote-projects ("Edit on Github" button)
* https://mlem.ai/doc/user-guide/data ("Edit on Github" button)
* https://mlem.ai/doc/get-started/deploying (["Service deployed"](https://github.com/iterative/example-mlem-get-started/tree/8-deploy-create))
* https://mlem.ai/doc/get-started/applying (["Evaluation"](https://github.com/iterative/example-mlem-get-started/tree/4-eval) and ["data saved with MLEM"](https://mlem.ai/doc/user-guide/datasets))

UPDATED list: https://github.com/iterative/mlem.ai/issues/109#issuecomment-1177877808

**Comment by jorgeorpinel** [comment]
@julieg18 does the engine itself include the link checker (just need to activate it) or is that something we have to setup separately and custom for each repo? Is it too hard to apply it to this one as a CI check for PRs? Thanks

**Comment by julieg18** [comment]
> @julieg18 does the engine itself include the link checker (just need to activate it) or is that something we have to setup separately and custom for each repo? Is it too hard to apply it to this one as a CI check for PRs? Thanks

The engine itself does not come with a link checker. It needs to be added separately (#101) with github actions and config files. It's already set up for mlem.ai though :) On [prs ](https://github.com/iterative/mlem.ai/actions/workflows/link-check-deploy.yml)and on [the whole repo](https://github.com/iterative/mlem.ai/actions/workflows/link-check-all.yml).

**Comment by rogermparent** [comment]
Worth noting I messed up the config for the whole-site check, and only noticed and fixed it recently. [The latest check runs](https://github.com/iterative/mlem.ai/runs/7224937433?check_suite_focus=true) now reflect all broken links.
```
* content/home-slides.js
  - https://dog-bark-translator.iterative.ai/ = https://dog-bark-translator.iterative.ai/ (Site not found)
* content/docs/command-reference/serve.md
  - https://docs.python-requests.org/ = https://docs.python-requests.org/ (ERR_TLS_CERT_ALTNAME_INVALID: request to https://docs.python-requests.org/ failed, reason: Hostname/IP does not match certificate's altnames: Host: docs.python-requests.org. is not in the cert's altnames: DNS:*.ispapi.net, DNS:ispapi.net)
* content/docs/contributing/core.md
  - /doc/user-guide/contributing/docs = https://mlem.ai/doc/user-guide/contributing/docs (404)
* content/docs/contributing/docs.md
  - https://raw.githubusercontent.com/iterative/mlem.ai/master/content/docs/user-guide/contributing/docs.md (404)
* content/docs/get-started/applying.md
  - https://github.com/iterative/example-mlem-get-started/tree/4-eval (404)
  - /doc/user-guide/datasets = https://mlem.ai/doc/user-guide/datasets (404)
* content/docs/get-started/deploying.md
  - https://github.com/iterative/example-mlem-get-started/tree/8-deploy-create (404)
* content/docs/get-started/serving.md
  - http://localhost:8080/docs = http://localhost:8080/docs (ECONNREFUSED: request to http://localhost:8080/docs failed, reason: connect ECONNREFUSED 127.0.0.1:8080)
* content/docs/user-guide/analytics.md
  - https://github.com/iterative/mlem/mlem/analytics.py (404)
* content/docs/user-guide/configuration.md
  - /doc/command-reference/config = https://mlem.ai/doc/command-reference/config (404)
* src/components/SEO/index.tsx
  - https://dvc.org/pl/api/event (404)
```

**Comment by jorgeorpinel** [comment]
Cc @aguschin
