### ISSUE TITLE
GS: more feedback

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem.ai#129]
Specific improvements to existing content.

- [x] What is **Saving models** about? Codification? Adopting GitOps? Possibly rename + emphasize the main purpose of `mlem.api.save`; Mention/link to `load()`?
  + Truncate code block (link to full file in example repo).
  + Show relevant parts of the .mlem file (link to full ").
  + Mention/link to other ML frameworks supported.
- [x] **Packaging models**: Intro is too long; Truncate code blocks;
  + Mention/link to other packagers available.
  + Hide "Exploring contents".
  + Extract "Pre-configured packagers" to User Guide.
  + Is it required for serving/deploying? If so is it done automatically by `serve|deploy`?
- [x] **Applying models**: Present it as a "batch alternative to serving/deploying" (per https://github.com/iterative/mlem.ai/pull/43#issuecomment-1128921109).
  + Use tabs to go from API to CLI? (This applies to most pages.)
- [x] **Serving models**: Summarize; Truncate sample output
  + "Making requests" could be a paragraph; Extract details to guide
- [x] **Deploying models**: Consolidate and maybe hide config (`create env|deployment`); Truncate sample output
  + "Making requests" could be a paragraph; Extract details to guide
  + Extract "Managing deployment" to UG
- [x] Export: better explain Docker instead of Python package. Docker export is much more widely used.
- [x] Move 4 use cases from the index page to the end of "Saving" section to say: "you just saved the model. Now you can use it in one of these ways:"
- [x] `mlem.api.apply` is less clear than `mlem.api.load` - while the 2nd is not explained in GS. Let's 1st with 2nd.

**Comment by aguschin** [comment]
related to https://github.com/iterative/mlem.ai/issues/58

**Comment by jorgeorpinel** [comment]
> related to https://github.com/iterative/mlem.ai/issues/58

Yeah we should consolidate these 2 tickets.

**Comment by aguschin** [comment]
@jorgeorpinel, I see you updated the description above. Some feedback looks outdated, so I assume this is the feedback for mlem.ai. Since #188 have more recent GS version, would be great if you adapt the feedback for that version.

Or you can keep it as it is, I'll apply what I think should be applied and then you'll TAL at #188 and we'll continue there.

**Comment by jorgeorpinel** [comment]
What I did here is to move all the specific suggestions from https://github.com/iterative/mlem.ai/issues/58 and kept that one only for more general feedback that may involve rewriting the GS. The specific ones here can be applied on top of existing GS I think. I see some are being addressed in https://github.com/iterative/mlem.ai/pull/188. 👍🏼

**Comment by aguschin** [comment]
@jorgeorpinel, @mike0sv. While rewriting Get Started to be pretty simple while demonstrating key Use Cases for MLEM, I'm tempted to showcase `local docker deploy` instead of Heroku. The reason: it's easier to reproduce locally. OFC I will mention Heroku, Sagemaker and K8s in the very first sentences on the page, but my concern is that it will be too toyish anyway. WDYT?

**Comment by aguschin** [comment]
Ok, I did everything with Heroku and I like it. No need to use local Docker deploy I think.

@jorgeorpinel, I think I addressed almost everything here. Except for:

> What is **Saving models** about? Codification? Adopting GitOps? Possibly rename + emphasize the main purpose of `mlem.api.save`; Mention/link to `load()`?
>   + Truncate code block (link to full file in example repo).
>   + Show relevant parts of the .mlem file (link to full ").
>   + Mention/link to other ML frameworks supported.

Could you please check out the [new GS index page](https://mlem-ai-new-docs-struct-hy95mv.herokuapp.com/doc/get-started)? Do we need to shorten the code block? Do we need to shorten YAML output? Is this ok to do?

My point: maybe it's long, but reproducible. This is what I would expect from GS, that should teach me the basic features of MLEM.

**Comment by aguschin** [comment]
Btw, if we're going to use another dataset (not iris), the training script will be longer. In that case, we'll have to extract details to some repo, I'm afraid. Rn the "pro" of the current GS is that we don't need any repo.

But still, we have `example-mlem-get-started` repo, which we can put to some use. Rn in #188 we use it only as a source of models to load (when we provide examples, we try to supply the urls to real model in that repo, so the command would run).

WDYT? @jorgeorpinel

**Comment by jorgeorpinel** [comment]
> tempted to showcase local docker deploy instead of Heroku... easier to reproduce locally.
but my concern is that it will be too toyish anyway. WDYT?

It's a good idea but installing Docker locally is kind of a pain from what I remember (and some features are not supported outside of Linux). Heroku seems more realistic indeed, and users who don't want to try it can get a good idea from just reading the GS (if it's well done).

> no need to explain what is MLEM Env

Didn't get what you meant there.

**Comment by jorgeorpinel** [comment]
> I think I addressed almost everything here

What about

- Is it ([Exporting models](https://mlem-ai-new-docs-struct-hy95mv.herokuapp.com/doc/get-started/building)) required for serving/deploying? If so is it done automatically by serve|deploy?
- Use tabs to go from API to CLI? (This applies to most pages.)
- Truncate sample output (multiple places)
  > Kind of a product question though: is `mlem` too verbose?
-  Move 4 use cases from the index page to the end of "Saving" section to say: "you just saved the model. Now you can use it in one of these ways:"
-  mlem.api.apply is less clear than mlem.api.load ... Let's 1st with 2nd.
  U: Now `apply()` is not used in [Applying models](https://mlem-ai-new-docs-struct-hy95mv.herokuapp.com/doc/get-started/applying). Is that OK?

> > What is Saving models about? ...
>
> please check out the new GS index page...

Nice. See [my review](https://github.com/iterative/mlem.ai/pull/188#pullrequestreview-1148464623).

Truncating code blocks in general is helpful (to emphasize the important parts of such code blocks AND to make the doc faster to read).

**Comment by aguschin** [comment]
Thanks for the feedback, @jorgeorpinel! Applied suggestion from your review as well, except for few things (left my comments there).

> Is it ([Exporting models](https://mlem-ai-new-docs-struct-hy95mv.herokuapp.com/doc/get-started/building)) required for serving/deploying? If so is it done automatically by serve|deploy?

No, serve is standalone. Build use serve under the hood. Deploy use build and serve under the hood. Explained this in get-started/building.

> Use tabs to go from API to CLI? (This applies to most pages.)

The only page that needs this, considering the current content, is `applying models.` We don't use this "tabs" mechanics anywhere on the mlem.ai, so let's keep it simple for users - for now. We'll get back to it once we start working on #190 

> Truncate sample output (multiple places)

Where exactly? The output may be verbose, but I think it's good to be clear in GS, to show people what is happening.

> Move 4 use cases from the index page to the end of "Saving" section to say: "you just saved the model. Now you can use it in one of these ways:"

Good idea. Did that, you can check it out.

> U: Now apply() is not used in [Applying models](https://mlem-ai-new-docs-struct-hy95mv.herokuapp.com/doc/get-started/applying). Is that OK?

Yes, it's not something we need in GS. It's covered in the CLI/API reference.

**Comment by jorgeorpinel** [comment]
> Build use serve under the hood. Deploy use build and serve under the hood. Explained this in get-started/building.

OK thanks for clarifying. TBH we don't need to mention this in GS (although a short note probably doesn't hurt either). In general it's better to leave implementation details for other sections of the docs 🙂 

> The output may be verbose, but I think it's good to be clear in GS

Yes it's probably a product question. I think MLEM output is too verbose. Is there an issue somewhere to discuss this?

**Comment by aguschin** [comment]
hooray, we have covered everything then. I'm closing the issue. Thanks for your effort @jorgeorpinel 🙏🏻

**Comment by jorgeorpinel** [comment]
Thank you.

**Comment by jorgeorpinel** [comment]
We still have #58 😬
