### ISSUE TITLE
docs: document how to specify a team name in Heroku

### ISSUE THREAD

**Issue by alex000kim** [iterative/mlem.ai#135]
Document `-c team=...` in https://mlem.ai/doc/get-started/deploying

**Comment by jorgeorpinel** [comment]
It's unclear in general where to find config options you can set with `create/deploy run -c`.

**Comment by aguschin** [comment]
This is obviously not the desired solution for users (we have [this issue](https://github.com/iterative/mlem/issues/233) for that), but one could find them in tests usually https://github.com/iterative/mlem/blob/main/tests/contrib/test_heroku.py

**Comment by aguschin** [comment]
is going to be closed with https://github.com/iterative/mlem/issues/233
