### ISSUE TITLE
guide: document config options (`-c`)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/mlem.ai#143]
> -c is being used as a catch-all and a way to avoid specifying the actual expected options for each command

The reason to use `-c` instead of `--<option name>` is because different implementations have different set of options. and adding options dynamically will probably require a lot of our cli framework butchering. we might do it later...

From documentation point of view, we need a dedicated page for each implementation (not only target envs, but other base classes too). It's huge amount of work but it needs to be done at some point

_Originally posted by @mike0sv in https://github.com/iterative/mlem/issues/233#issuecomment-1190869678_

**Comment by aguschin** [comment]
outdated, since we removed those in 0.3.0
