### ISSUE TITLE
guide: explain the structure of `.mlem/` folder

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem.ai#151]
> It would be worth to explain the structure of the `.mlem/` folder

reported by @Meleagos 

Currently, we have some information [here](https://mlem.ai/doc/user-guide/basic-concepts) and [here](https://mlem.ai/doc/user-guide/project-structure). I guess we need some section on the last page that will explain this. Otherwise, I'm not even sure how to get that info from the docs.

**Comment by jorgeorpinel** [comment]
https://mlem.ai/doc/user-guide/project-structure seems like the best place to put this now.

**Comment by aguschin** [comment]
closing since we're removing .mlem dir in new release
