### ISSUE TITLE
GS: show local Docker deploy in the end of Serve section

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem.ai#166]
We can showcase/give a hint about Local docker deploy in https://mlem.ai/doc/get-started/serving

Originally from https://github.com/iterative/mlem/issues/375#issuecomment-1233962553

**Comment by jorgeorpinel** [comment]
Isn't that part of https://mlem.ai/doc/get-started/deploying ? In fact it's already mentioned there.

**Comment by aguschin** [comment]
Not quite. This about a local serving. Effectively it's something like `mlem deploy docker mymodel`, that builds docker image and runs it (locally if not specified otherwise). Compare this to deploying to Heroku or Sagemaker - that happens on remote SaaS/machines. So while it's "deploy", it's very close to "serve".

Now the thing is, this `local docker deploy` is something that users may want to use as an alternative to running `mlem serve`. So it makes sense to mention and describe it there.

**Comment by jorgeorpinel** [comment]
> while it's "deploy", it's very close to "serve"

May I ask why not put it in the `build` or `serve` commands? (product Q)

> Compare this to deploying to Heroku or Sagemaker

BTW, should Sagemaker be at least mentioned in https://mlem.ai/doc/get-started/deploying now? (separate issue)

**Comment by aguschin** [comment]
It's definitely not `build`, because `build` doesn't run the models. Only bundles models into something.

Not so sure about `serve`. Let's ask @mike0sv why was the rationale behind this.

Sagemaker is not yet released. It's in a special branch https://github.com/iterative/mlem/tree/release/0.3.0, and we're going to release it on Pypi in a month or so.

**Comment by mike0sv** [comment]
it's not serve because serve is a continuous command and deploy is not. 
IMO serve docs are for serve, deployment docs are for deployments. Docker deployment is a deployment. So it's docs should go into deployment docs.
I don't agree that docker deployment is something more than serving and less than deployment. You can deploy to remote docker daemons as well. Yes, local docker can be referenced in serve docs as a next step, but to use it user should understand the basics of MLEM deployments

**Comment by aguschin** [comment]
> it's not serve because serve is a continuous command and deploy is not.

That's just because you detach from the docker container you're running. If you won't detach, it would be continuous. So if you won't detach by default (like `docker` CLI does), it would be in `serve`.

**Comment by jorgeorpinel** [comment]
I also think it would be better to cover it in https://mlem.ai/doc/get-started/deploying or in other `deploy`-specific page. But you could add a tip admonition in https://mlem.ai/doc/get-started/serving mentioning that local deploys are similar to serving, or something like that.

**Comment by mike0sv** [comment]
@aguschin I talked about mlem serve and mlem deploy, not docker. The difference is that `mlem serve` IS the process that servers, while `mlem deploy` runs that serving process somewhere else (docker or no docker, cloud or local). And for this to work we have state and other deployment-related stuff that we need to teach users

**Comment by jorgeorpinel** [comment]
> mlem serve IS the process that serves, while mlem deploy runs that serving process somewhere else

I think that these are implementation details though. For docs we should care more about the end function/ value features give the user (UX). So I second @aguschin's observation that if it didn't detach by default, it would be an equivalent function as serving. Probably to consider in the future: I don't expect the CLI design to change over this now.

**Comment by mike0sv** [comment]
It's not about "default" behavior, `mlem deploy` cannot "not detach"

**Comment by aguschin** [comment]
Ok, that was a good discussion above, thank you guys. Since we're simplying GS as much as possible, there is no place to local Docker deploy in the end of Serve section, except for a simple mention. I'll see if that fits. Closing this issue.
