### ISSUE TITLE
Some links are failing

### ISSUE THREAD

**Issue by rogermparent** [iterative/mlem.ai#299]
From https://github.com/iterative/mlem.ai/actions/runs/4049385922/jobs/6965683963

* content/docs/get-started/index.md
  - FAIL: /doc/user-guide-serving/fastapi = https://mlem.ai/doc/user-guide-serving/fastapi (404)
  - FAIL: /doc/user-guide/serving/rabbitmnq = https://mlem.ai/doc/user-guide/serving/rabbitmnq (404)
* content/docs/user-guide/basic-concepts.md
  - FAIL: /doc/user-guide/api-reference/save = https://mlem.ai/doc/user-guide/api-reference/save (404)

**Comment by yathomasi** [comment]
It seems to me that, they are mostly typo errors or wrong references. For eg: 
- https://mlem.ai/doc/user-guide-serving/fastapi ==>> https://mlem.ai/doc/user-guide/serving/fastapi/
-  /doc/user-guide/serving/rabbitmnq -> either it's WIP or shouldn't be linked as it's not in mlem.ai page
- I guess https://mlem.ai/doc/user-guide/api-reference/save ==>> https://mlem.ai/doc/api-reference/save/

cc: @aguschin @jorgeorpinel

**Comment by aguschin** [comment]
Hi guys! Thank you for reporting this! Fixed in https://github.com/iterative/mlem.ai/pull/300, can you please review?

**Comment by yathomasi** [comment]
Waiting for deployment to complete and `link-checker` to pass.

**Comment by rogermparent** [comment]
I totally made a quick branch for this and didn't make a PR :facepalm: thanks for the fix @aguschin!
