### ISSUE TITLE
prism: we need both `dvc` and `mlem` highlighters

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/mlem.ai#59]
_Originally posted by @jorgeorpinel in https://github.com/iterative/mlem.ai/pull/43#discussion_r875199987_

**Comment by yathomasi** [comment]
> @yathomasi can we have this ported to cml.dev too? 🙏

@casperdcl It's already available. 

- [example](https://github.com/iterative/cml.dev/blob/32970cd198d9718a12847bb96930a411c462a2ed/content/docs/ref/ci.md?plain=1#L28-L30)  Live => [cml.dev/doc/ref/ci](https://cml.dev/doc/ref/ci)
- Also, opened a issue for content update https://github.com/iterative/cml.dev/issues/239
