### ISSUE TITLE
home: featured texts

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/mlem.ai#65]
_Extracted from https://github.com/iterative/mlem.ai/pull/51#pullrequestreview-974549878_

<img width="951" alt="image" src="https://user-images.githubusercontent.com/1477535/169628831-31972a25-d3c0-4fcc-afb4-c41a74144706.png">

From home page: https://mlem.ai/

First, the idea is to show a basic workflow and main features, right? Keeping that in mind...

1.

> Save your model with a single command

What command? The slide shows a Python call (`model.api.save()`)

2.

> Use simple YAML file to save model metadata

Not sure the YAML format is simple or whether that matters much. Maybe "Model metadata is captured automatically" (mention "YAML format" in subtext if needed).

3.

> Switch between deployment providers with a single command

Minor: Is "deployment provider" a common term? Production environments? Cloud providers? Servers? Hosting?

**Comment by aguschin** [comment]
> What command? The slide shows a Python call (model.api.save())

If that sounds incorrect to you, let's name the section `Save your model with a single Python call` or something. WDYT?

> Not sure the YAML format is simple or whether that matters much. Maybe "Model metadata is captured automatically" (mention "YAML format" in subtext if needed).

For me, "YAML" conveys the point that it is some readable text. Which explains how it works a bit, and that's good. But I see your point. "Model metadata is captured automatically" looks good to me also.

> Minor: Is "deployment provider" a common term? Production environments? Cloud providers? Servers? Hosting?

Thanks. "deployment platform" should be better I think, taking into account the meaning and the number of pages found in google.
