### ISSUE TITLE
Add number of Github stars to website

### ISSUE THREAD

**Issue by yathomasi** [iterative/mlem.ai#97]
References: 
<img width="400" alt="Screen Shot 2022-06-07 at 09 36 36" src="https://user-images.githubusercontent.com/20840228/172292173-7487e345-6dc0-4423-8d77-568e0ea28ba1.png"><img width="400" alt="Screen Shot 2022-06-07 at 09 36 49" src="https://user-images.githubusercontent.com/20840228/172292209-c8e5e276-fad0-4eaf-93bf-5ce444d30718.png">

**Comment by julieg18** [comment]
@yathomasi, did someone request this? If not, we may want to wait until `mlem` has more stars 🤔 before adding this.

**Comment by yathomasi** [comment]
> @yathomasi, did someone request this? If not, we may want to wait until `mlem` has more stars before adding this 🤔

It was mentioned by Ivan. Sure, we can have the setup and merge whenever we fell suitable.

**Comment by julieg18** [comment]
> It was mentioned by Ivan. Sure, we can have the setup and merge whenever we fell suitable.

No problem! We can go ahead and merge once your pr is ready and approved :)
